//
//  OSCTCPClient Notification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2026 Steffan Andrews • Licensed under MIT License
//

import Network

extension OSCTCPClient {
    /// A notification event generated by the TCP client.
    public enum Notification {
        /// The client successfully connected to the remote server.
        case connected
        
        /// The client was disconnected from the remote server.
        /// If the disconnection was a result of an error, the error will be non-nil.
        case disconnected(error: NWError?)
    }
}

extension OSCTCPClient.Notification: Equatable { }
    
extension OSCTCPClient.Notification: Hashable { }
    
extension OSCTCPClient.Notification: Sendable { }
